/****************************************************************************************************/
/*                                                                                                  */
/* File: Tooltips.java                                                                              */
/* Description: Lookup table for help tool tips                                                     */
/* Created: 2021-2022 in Mexico                                                                     */
/* License type: Apache                                                                             */
/*                                                                                                  */
/* Author: Luis Olea                                                                                */
/*                                                                                                  */
/****************************************************************************************************/

public class ToolTips {
static String[][] text = {
{"alter disk-store","Alter some options for a region or remove a region in an offline disk store."},
{"alter region","Alter a region with the given path and configuration."},
{"alter runtime","Alter a subset of member or members configuration properties while running."},
{"backup disk-store","Perform a backup on all members with persistent data. The target directory must exist on all members, but can be either local or shared. This command can safely be executed on active members and is strongly recommended over copying files via operating system commands."},
{"change loglevel","This command changes log-level run time on specified servers."},
{"clear defined indexes","Clears all the defined indexes."},
{"close durable-client","Attempts to close the durable client, the client must be disconnected."},
{"close durable-cq","Closes the durable cq registered by the durable client and drain events held for the durable cq from the subscription queue."},
{"compact disk-store","Compact a disk store on all members with that disk store. This command uses the compaction threshold that each member has configured for its disk stores. The disk store must have allow-force-compaction set to true."},
{"compact offline-disk-store","Compact an offline disk store. If the disk store is large, additional memory may need to be allocated to the process using the --J=-Xmx??? parameter."},
{"configure pdx","Configures GemFire's Portable Data eXchange for all the cache(s) in the cluster. This command would not take effect on the running members in the system."},
{"connect","Connect to a jmx-manager either directly or via a Locator. If connecting via a Locator, and a jmx-manager doesn't already exist, the Locator will start one."},
{"create async-event-queue","Create Async Event Queue."},
{"create defined indexes","Creates all the defined indexes."},
{"create disk-store","Create a disk store."},
{"create gateway-receiver","Create the Gateway Receiver on a member or members."},
{"create gateway-sender","Create the Gateway Sender on a member or members."},
{"create index","Create an index that can be used when executing queries."},
{"create region","Create a region with the given path and configuration. Specifying a --key-constraint and --value-constraint makes object type information available during querying and indexing."},
{"debug","Enable/Disable debugging output in GFSH."},
{"define index","Define an index that can be used when executing queries."},
{"deploy","Deploy JARs to a member or members.  Only one of either --jar or --dir may be specified."},
{"describe client","Display details of specified client"},
{"describe config","Display configuration details of a member or members."},
{"describe connection","Display information about the current connection."},
{"describe disk-store","Display information about a member's disk store."},
{"describe member","Display information about a member, including name, id, groups, regions, etc."},
{"describe offline-disk-store","Display information about an offline disk store."},
{"describe region","Display the attributes and key information of a region."},
{"destroy disk-store","Destroy a disk store, including deleting all files on disk used by the disk store. Data for closed regions previously using the disk store will be lost."},
{"destroy function","Destroy/Unregister a function. The default is for the function to be unregistered from all members."},
{"destroy index","Destroy/Remove the specified index."},
{"destroy region","Destroy/Remove a region."},
{"disconnect","Close the current connection, if one is open."},
{"echo","Echo the given text which may include system and user variables."},
{"encrypt password","Encrypt a password for use in data source configuration."},
{"execute function","Execute the function with the specified ID. By default will execute on all members."},
{"exit","Exit GFSH and return control back to the calling process."},
{"export cluster-configuration","Exports the cluster configuration artifacts as a zip file."},
{"export config","Export configuration properties for a member or members."},
{"export data","Export user data from a region to a file."},
{"export logs","Export the log files for a member or members."},
{"export offline-disk-store","Export region data from an offline disk store into gemfire snapshot files."},
{"export stack-traces","Export the stack trace for a member or members."},
{"gc","Force GC (Garbage Collection) on a member or members. The default is for garbage collection to occur on all caching members."},
{"get","Display an entry in a region. If using a region whose key and value classes have been set, then specifying --key-class and --value-class is unnecessary."},
{"help","Display syntax and usage information for all commands or list all available commands if <command> isn't specified."},
{"hint","Provide hints for a topic or list all available topics if topic isn't specified."},
{"history","Display or export previously executed GFSH commands."},
{"import cluster-configuration","Imports configuration into cluster configuration hosted at the locators"},
{"import data","Import user data from a file to a region."},
{"list async-event-queues","Display the Async Event Queues for all members."},
{"list clients","Display list of connected clients"},
{"list deployed","Display a list of JARs that were deployed to members using the deploy command."},
{"list disk-stores","Display disk stores for all members."},
{"list durable-cqs","List durable client cqs associated with the specified durable client id."},
{"list functions","Display a list of registered functions. The default is to display functions for all members."},
{"list gateways","Display the Gateway Senders and Receivers for a member or members."},
{"list indexes","Display the list of indexes created for all members."},
{"list members","Display all or a subset of members."},
{"list regions","Display regions of a member or members."},
{"load-balance gateway-sender","Cause the Gateway Sender to close its current connections so that it reconnects to its remote receivers in a more balanced fashion."},
{"locate entry","Identifies the location, including host, member and region, of entries that have the specified key."},
{"netstat","Report network information and statistics via the netstat operating system command."},
{"pause gateway-sender","Pause the Gateway Sender on a member or members."},
{"pdx rename","Renames PDX types in an offline disk store."},
{"put","Add/Update an entry in a region. If using a region whose key and value classes have been set, then specifying --key-class and --value-class is unnecessary."},
{"query","Run the specified OQL query as a single quoted string and display the results in one or more pages. Limit will default to the value stored in the APP_FETCH_SIZE variable. Page size will default to the value stored in the APP_COLLECTION_LIMIT variable."},
{"rebalance","Rebalance partitioned regions. The default is for all partitioned regions to be rebalanced."},
{"remove","Remove an entry from a region. If using a region whose key class has been set, then specifying --key-class is unnecessary."},
{"resume gateway-sender","Resume the Gateway Sender on a member or members."},
{"revoke missing-disk-store","Instructs the member(s) of a distributed system to stop waiting for a disk store to be available. Only revoke a disk store if its files are lost as it will no longer be recoverable once revoking is initiated. Use the show missing-disk-store command to get descriptions of missing disk stores."},
{"run","Execute a set of GFSH commands. Commands that normally prompt for additional input will instead use default values."},
{"set variable","Set GFSH variables that can be used by commands. For example: if variable CACHE_SERVERS_GROUP is set then to use it with list members, use list members --group=${CACHE_SERVERS_GROUP}. The echo command can be used to know the value of a variable."},
{"sh","Allows execution of operating system (OS) commands. Use '&' to return to gfsh prompt immediately. NOTE: Commands which pass output to another shell command are not currently supported."},
{"show dead-locks","Display any deadlocks in the GemFire distributed system."},
{"show log","Display the log for a member."},
{"show metrics","Display or export metrics for the entire distributed system, a member or a region."},
{"show missing-disk-stores","Display a summary of the disk stores that are currently missing from a distributed system."},
{"show subscription-queue-size","Shows the number of events in the subscription queue.  If a cq name is provided, counts the number of events in the subscription queue for the specified cq."},
{"shutdown","Stop all members."},
{"sleep","Delay for a specified amount of time in seconds - floating point values are allowed."},
{"start gateway-receiver","Start the Gateway Receiver on a member or members."},
{"start gateway-sender","Start the Gateway Sender on a member or members."},
{"start jconsole","Start the JDK's JConsole tool in a separate process. JConsole will be launched, but connecting to GemFire must be done manually."},
{"start jvisualvm","Start the JDK's Java VisualVM (jvisualvm) tool in a separate process. Java VisualVM will be launched, but connecting to GemFire must be done manually."},
{"start locator","Start a Locator."},
{"start pulse","Open a new window in the default Web browser with the URL for the Pulse application."},
{"start server","Start a GemFire Cache Server."},
{"start vsd","Start VSD in a separate process."},
{"status cluster-config-service","Displays the status of cluster configuration service on all the locators with enable-cluster-configuration set to true."},
{"status gateway-receiver","Display the status of a Gateway Receiver."},
{"status gateway-sender","Display the status of a Gateway Sender."},
{"status locator","Display the status of a Locator. Possible statuses are: started, online, offline or not responding."},
{"status server","Display the status of a GemFire Cache Server."},
{"stop gateway-receiver","Stop the Gateway Receiver on a member or members."},
{"stop gateway-sender","Stop the Gateway Sender on a member or members."},
{"stop locator","Stop a Locator."},
{"stop server","Stop a GemFire Cache Server."},
{"undeploy","Undeploy JARs from a member or members."},
{"upgrade offline-disk-store","Upgrade an offline disk store. If the disk store is large, additional memory may need to be allocated to the process using the --J=-Xmx??? parameter."},
{"validate offline-disk-store","Scan the contents of a disk store to verify that it has no errors."},
{"version","Display product version information."}
};
}